== YANG Tools
YANG is a data modelling language used to model configuration and state data manipulated by the Network Configuration Protocol(NETCONF), NETCONF remote procedure calls, and NETCONF notifications.
YANG is used to model the operations and content layers of NETCONF.

=== Prerequisites for YANG Tools Project
* OpenDayLight account +
  https://identity.opendaylight.org/carbon/user-registration/index.jsp?region=region1&item=user_registration_menu[Get an account] to push or edit code on the wiki. You can however pull code anonymously.
* Gerrit Setup for code review +
  To use shh follow instructions on  Opendaylight wiki page at: https://wiki.opendaylight.org/view/OpenDaylight_Controller:Gerrit_Setup +
  To use https follow instructions on  Opendaylight wiki page at: https://wiki.opendaylight.org/view/OpenDaylight_Controller:Setting_up_HTTP_in_Gerrit
* Maven 3 to import Maven project from OpendayLight Git repository +
  To clone the controller follow instructions at: https://git.opendaylight.org/gerrit/p/controller.git  +
  To clone the yangtools repositories follow instructions at: https://git.opendaylight.org/gerrit/p/yangtools.git

NOTE: You need to setup Gerrit  to access GIT using ssh.

=== Pulling code using ssh
To pull code using ssh use the following command: +

	git clone ssh://${ODL_USERNAME}@git.opendaylight.org:29418/yangtools.git;(cd yangtools; scp -p -P 29418 ${ODL_USERNAME}@git.opendaylight.org:hooks/commit-msg .git/hooks/;chmod 755 .git/hooks/commit-msg;git config remote.origin.push HEAD:refs/for/master)

=== Pulling code using https
To pull code using https, use the following command: +

	git clone https://git.opendaylight.org/gerrit/p/yangtools.git;(cd yangtools; curl -o .git/hooks/commit-msg https://git.opendaylight.org/gerrit/tools/hooks/commit-msg;chmod 755 .git/hooks/commit-msg;git config remote.origin.push HEAD:refs/for/master)

=== Building the code
To build the code, increase the memory available for Maven. The settings on the Jenkins build server are: +

	export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=256m"

IMPORTANT: The top level build line for yangtools project is: `cd yangtools;mvn clean install`
